nelmio_api_doc:
    documentation:
        info:
            title: 'Blog API Documentation'
            description: 'Diese API verwendet JWT-Authentifizierung und ermöglicht das Erstellen, Bearbeiten und Löschen von Blogposts.'
            version: '1.0.0'
            contact:
                name: 'Jens Smit'
                url: 'https://github.com/Jens-Smit'
                email: 'info@jenssmit.de'
            license:
                name: 'MIT'
                url: 'https://opensource.org/licenses/MIT'
    areas:
        default:
            path_patterns: [ ^/ ]  # Dokumentiert alle Routen
    