# config/packages/rate_limiter.yaml
framework:
    rate_limiter:
        login_limiter:
            policy: 'sliding_window'
            limit: 5
            interval: '15 minutes'
            
        password_reset_limiter:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
            
        token_refresh_limiter:
            policy: 'sliding_window'
            limit: 20
            interval: '1 hour'
            
        api_general:
            policy: 'sliding_window'
            limit: 100
            interval: '1 minute'